apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres
    access: proxy
    url: postgres:5432
    user: agrivision
    secureJsonData:
      password: agrivision
    jsonData:
      database: agrivision
      sslmode: disable
    isDefault: true
